version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
