services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
