version: '3.8'

services:
  frontend:
    build: "C:/Users/sujal/Desktop/courses_api/courses_frontend"  
    container_name: react_frontend
    ports:
      - "3000:3000"

  backend:
    build: "C:/Users/sujal/Desktop/courses_api/coursesbackend"  
    container_name: django_backend
    ports:
      - "8000:8000"
